export const ROUTES = {
  LOGIN: 'Login',
  REGISTER: 'Register',
  DASHBOARD: 'Dashboard',
  PROFILE: 'Profile',
  SHOWCASE: 'Showcase',
  GLOBAL_STOCK: 'GlobalStock',
  PRODUCT_FORM: 'ProductForm',
  PRODUCT_DETAILS: 'ProductDetails',
  PUBLIC_PROFILE: 'PublicProfile',
  CHECKOUT: 'Checkout',
  MY_RESERVATIONS: 'MyReservations',
  MY_TRANSACTIONS: 'MyTransactions',
  MY_CHATS: 'MyChats',
  MY_CASHBOX: 'MyCashbox',
  TRANSACTION_DETAILS: 'TransactionDetails',
  CHAT_ROOM: 'ChatRoom',
  ADMIN_DASHBOARD: 'AdminDashboard',
  ADMIN_USERS: 'AdminUsers'
};
